FROM python:3.14.0

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates

ADD https://astral.sh/uv/install.sh /uv-installer.sh

RUN sh /uv-installer.sh && rm /uv-installer.sh

ENV PATH="/root/.local/bin/:$PATH"

COPY requirements.txt .

RUN uv pip install --system -r requirements.txt

COPY . .

CMD [ "python", "app.py" ]
