[sources.sql_database.credentials]
drivername = "<configure me>" # fill this in!
database = "<configure me>" # fill this in!
password = "<configure me>" # fill this in!
username = "<configure me>" # fill this in!
host = "<configure me>" # fill this in!
port = 0 # fill this in!

[destination.postgres.credentials]
database = "customer_db" # fill this in!
password = "password" # fill this in!
username = "postgres" # fill this in!
host = "localhost" # fill this in!
port = 5432
connect_timeout = 15
